# Blog info
blog_name: Star
slogan: 简单点，快乐点
url: http://huirong.github.io

# Set avatar (Absolute url and relative url) 设置头像
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: jackroyal 博客 搁浅St 笨笨

# 设置首页导航
home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Github
    url: https://github.com/huirong
    target_blank: true

# config page nav 页面导航
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  #- name: RSS
  #  url: /atom.xml
  #  target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: 让我猜猜你在找什么 o(≧v≦)o~~

link_slogan:
  isShow: true # true|fase
  text: 交换友链可以邮件 huirong1111@gmail.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: 支持一下
  tip: 走过的，路过的，请支持一下我 n(*≧▽≦*)n
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
#    - type: 支付宝
#      text: 支付宝扫一扫
#      imgUrl: /images/qr-alipay.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style
personal_style: /css/huirong.css

home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: 13fd5daa6d82a4022fb7211641792382

# Comment service
#disqus_shortname: star
# duoshuo_shortname: forsigner


# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "想做个安全界的萌妹子，可惜颜值不够，只能专心搞安全了~~~~~"
    - "爱看小说，爱睡懒觉"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@huirong"
    text_value_url: https://github.com/huirong
  # - type: weibo
  #   icon: icon-weibo
  #   text_key: 微博
  #   text_value: "@forsigner"
  #   text_value_url: http://weibo.com/u/1847075964
  - type: mail
    icon: icon-mail
    text_key: Gmail
    text_value: "huirong1111@gmail.com"
  - type: location
    icon: icon-location
    text_value: 武汉

link:
  - name: jackroyal
    info: 我最喜欢笨笨
    url: http://bblove.me/
    avatar: http://ww3.sinaimg.cn/large/005CA6ZCgw1f7isnieoomj3085064gm6.jpg
  - name: moon 的博客
    info: 她也喜欢我~~
    url: http://moonmoonmoon.github.io/
    avatar: http://ww4.sinaimg.cn/large/005CA6ZCgw1f7isleabh9j305k05kdfw.jpg
  

#project:
#  - type: personal
#    name: fexo
#    url: https://github.com/forsigner/fexo
#    intro: A minimalist design theme for hexo

